version: "3.7"
services:
  expense-tracker-db:
    restart: always
    container_name: expense-tracker-db
    image:  postgres:14
    environment:
      - POSTGRES_PASSWORD=****
      - POSTGRES_USER=*****
      - POSTGRES_DB=expensedb

    volumes:
        - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  expense-tracker-api:
    restart: on-failure
    build: ./
    image: spring-boot-expense-tracker
    container_name: expense-tracker-api
    expose:
      - "8080"
      - "5006"
    ports:
      - "8080:8080"
      - "5006:5006"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://expense-tracker-db:5432/expensedb
      - SPRING_DATASOURCE_USERNAME=****
      - SPRING_DATASOURCE_PASSWORD=*****
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - expense-tracker-db